### ISSUE TITLE
Fix kubia-deployment-v3-with-readinesscheck.yaml [Chapter09]

### ISSUE THREAD

**Issue by Alban-K** [luksa/kubernetes-in-action#50]
error: resource mapping not found for name: "kubia" namespace: "" from "kubia-deployment-v3-with-readinesscheck.yaml": no matches for kind "Deployment" in version "apps/v1beta1"
ensure CRDs are installed first

**Comment by Alban-K** [comment]
fix
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  selector:
    matchLabels:
      app: kubia
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - image: luksa/kubia:v3
        name: nodejs
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 8080

```
